// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSYeohcmUojwnom6U9P-Jutw2QBx6g4jA',
    appId: '1:1001319703200:android:68e1fb700d9d6849f75fc5',
    messagingSenderId: '1001319703200',
    projectId: 'firebase-for-gatherupapp',
    databaseURL: 'https://firebase-for-gatherupapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'firebase-for-gatherupapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjCPASPYOq818gx86_6S2yvjZbCXTJ_PY',
    appId: '1:1001319703200:ios:f24046ee375a2569f75fc5',
    messagingSenderId: '1001319703200',
    projectId: 'firebase-for-gatherupapp',
    databaseURL: 'https://firebase-for-gatherupapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'firebase-for-gatherupapp.firebasestorage.app',
    iosBundleId: 'com.quizradar.quizradar',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAedytijIdKclIsjxy77hwG0izhZeMFNHw',
    appId: '1:1001319703200:web:850bbbf9917481e3f75fc5',
    messagingSenderId: '1001319703200',
    projectId: 'firebase-for-gatherupapp',
    authDomain: 'fir-for-gatherupapp.firebaseapp.com',
    databaseURL: 'https://firebase-for-gatherupapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'firebase-for-gatherupapp.firebasestorage.app',
  );

}